#page title
page_title                                : Argon Mail                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : ArgonMail.net

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : JESO                         
your_link                                 :                    
your_city                                 :                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Argonmail
    description                           : ArgonMail.net is an e-mail service provider that is currently undergoing development and expansion. Currently, we have a limited number of accounts for testing purposes and are not setting up accounts for public use.
    fontawesome_icon_name                 : magic
    
  - title                                 : Project Goals
    description                           : We are working on a comprehensive suite of personal calendars, reminder or to-do lists, and e-mail web client, which will be seamlessly integrated with a mobile app.
    fontawesome_icon_name                 : mobile

  - title                                 : Break Barriers
    description                           : Our future focus at ArgonMail is customizability to fit your work flow. Rather than having a traditional e-mail welcome page, we hope to create a more interactive, integrative experience that allows you to send, receive, and consume e-mails in a free-flowing, innovative fashion.
    fontawesome_icon_name                 : play-circle

  - title                                 : For all your needs
    description                           : We know that all the big box brands provide “free” services that are all available in a comprehensive suite. That’s why we are committed to having a complete package before releasing it to the public.
    fontawesome_icon_name                 : sync

  - title                                 : About us
    description                           : We are a group of like-minded individuals who wanted to create something different. This project is still very early in its infancy, as most of us have our regular day jobs. As things progress, we will continue to update this website - JESO
    fontawesome_icon_name                 : adjust
  
  -


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :minify # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
